export const quotes = [
    "Imagination is more important than knowledge.",
    "If I have seen further, it is by standing on the shoulders of giants.",
    "Nothing in life is to be feared, it is only to be understood.",
    "The present is theirs; the future, for which I really worked, is mine.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "Nature isn’t classical, dammit, and if you want to make a simulation of nature, you’d better make it quantum mechanical.",
    "The cosmos is within us. We are made of star-stuff.",
    "Remember to look up at the stars and not down at your feet.",
    "To invent, you need a good imagination and a pile of junk.",
    "The only way to do great work is to love what you do.",
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "We can complain because rose bushes have thorns, or rejoice because thorns have roses.",
    "The future depends on what we do in the present.",
    "In science, there are no shortcuts to truth.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Life is really simple, but we insist on making it complicated.",
    "The way to get started is to quit talking and begin doing.",
    "I would rather die of passion than of boredom.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "In the middle of difficulty lies opportunity.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "A person who never made a mistake never tried anything new.",
    "The measure of intelligence is the ability to change.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "If you want to find the secrets of the universe, think in terms of energy, frequency, and vibration.",
    "The more I learn, the more I realize how much I don't know.",
    "Science is the great antidote to the poison of enthusiasm and superstition.",
    "The true sign of intelligence is not knowledge but imagination.",
    "The best way to predict the future is to create it.",
    "The only thing that interferes with my learning is my education.",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    "A person who never made a mistake never tried anything new.",
    "We cannot solve our problems with the same thinking we used when we created them.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "We can complain because rose bushes have thorns, or rejoice because thorns have roses.",
    "In the middle of difficulty lies opportunity.",
    "Imagination is everything. It is the preview of life's coming attractions.",
    "I have no special talent. I am only passionately curious.",
    "The true sign of intelligence is not knowledge but imagination.",
    "The more I learn, the more I realize how much I don't know.",
    "In science, there are no shortcuts to truth.",
    "Science is the great antidote to the poison of enthusiasm and superstition.",
    "The future depends on what we do in the present.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "To invent, you need a good imagination and a pile of junk.",
    "The only way to do great work is to love what you do.",
    "If you want to find the secrets of the universe, think in terms of energy, frequency, and vibration.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "I would rather die of passion than of boredom.",
    "The best way to predict the future is to create it.",
    "The measure of intelligence is the ability to change.",
    "The only thing that interferes with my learning is my education.",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    "The most beautiful experience we can have is the mysterious.",
    "The important thing is not to stop questioning.",
    "You have to learn the rules of the game. And then you have to play better than anyone else.",
    "The difference between stupidity and genius is that genius has its limits.",
    "Logic will get you from A to B. Imagination will take you everywhere.",
    "The only true wisdom is in knowing you know nothing.",
    "We are all in the gutter, but some of us are looking at the stars.",
    "I never made one of my discoveries through the process of rational thinking.",
    "Everything should be made as simple as possible, but not simpler.",
    "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "It's not that I'm so smart, it's just that I stay with problems longer.",
    "The only real valuable thing is intuition.",
    "A man who dares to waste one hour of time has not discovered the value of life.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "I find that the harder I work, the more luck I seem to have.",
    "Don't count the days, make the days count.",
    "The only place where success comes before work is in the dictionary.",
    "If you don't value your time, neither will others. Stop giving away your time and talents. Value what you know and start charging for it.",
    "I have learned over the years that when one's mind is made up, this diminishes fear; knowing what must be done does away with fear.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
    "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
    "The successful warrior is the average man, with laser-like focus.",
    "The best revenge is massive success.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "Don't watch the clock; do what it does. Keep going.",
    "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The secret to getting ahead is getting started.",
    "Don't be afraid to give up the good to go for the great.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only thing that will stop you from fulfilling your dreams is you.",
    "The road to success and the road to failure are almost exactly the same.",
    "Success is not in what you have, but who you are.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The only place where success comes before work is in the dictionary.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "I find that the harder I work, the more luck I seem to have.",
    "Don't count the days, make the days count.",
    "The only real valuable thing is intuition.",
    "A man who dares to waste one hour of time has not discovered the value of life.",
    "The only thing that will stop you from fulfilling your dreams is you.",
    "The road to success and the road to failure are almost exactly the same.",
    "Success is not in what you have, but who you are."
]